#pragma once
#include <iostream>
#include <string>
#include <cstdio>
#include <vector>
#include <algorithm>
#include <typeinfo>
#include <math.h>
#include <ctime>
#include <fstream>
#include <sstream>
#include <stdlib.h>

using std::vector;
using std::cout;
using std::cin;
using std::endl;
using std::string;
using std::sort;
using std::to_string;
using std::generate;
using std::ifstream;
using std::stringstream;
using std::remove_if;
using std::exception;